### PR TITLE
expose stderr

### LINKED ISSUE #4: Stderr is ignored
Stderr is ignored. Should be returned both for exit code zero and non-zero exit code.

### PR DESCRIPTION
**Pull request by jetersen**
fixes #4 

There is probably a better or preferred way to expose stderr but this is good enough for my try and catch use case. We could do something similar to https://github.com/expo/spawn-async but i prefer the simplicity of this one.

In any case I am open to suggestions 👍

### CODE REVIEW

**Comment by ralphtheninja** [comment]
LGTM!

@abrkn Anything to add?

**Comment by ralphtheninja** [comment]
Actually, maybe we should just `reject(stderr)`?

**Comment by jetersen** [comment]
I would prefer the returned was an error object. We can always assign the stderr to the error object which we properly should :)

**Comment by ralphtheninja** [comment]
@casz Thanks! I'll tweak it a bit and update README etc before I release it.

**Comment by ralphtheninja** [comment]
2.1.0

**Comment by jetersen** [comment]
@ralphtheninja 👍 for taking it into the finish line will update my project asap 🥁

**Pull request merged**
